# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build app in debug and release"
  lane :assemble do
    gradle(task: "assemble")
  end

  desc "Run unit tests"
  lane :unit_test do
    gradle(task: "test")
  end

  desc "Run instrumentation tests"
  lane :instrumentation_test do
    gradle(task: "connectedCheck")
  end

  desc "Build & deploy release to Google Play internal track"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'internal')
  end
end
